// ==UserScript==
// @name         orangui: Teams
// @namespace    scadoshi
// @version      0.3.1
// @description  zwipe's look and its 31 themes for Teams on the web. Alt+Shift+T opens the theme picker.
// @author       scadoshi
// @homepageURL  https://github.com/scadoshi/orangui
// @updateURL    https://raw.githubusercontent.com/scadoshi/orangui/main/orangui-teams.user.js
// @downloadURL  https://raw.githubusercontent.com/scadoshi/orangui/main/orangui-teams.user.js
// @match        https://teams.microsoft.com/*
// @match        https://teams.cloud.microsoft/*
// @run-at       document-start
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_addValueChangeListener
// @grant        GM_registerMenuCommand
// ==/UserScript==

(() => {
  'use strict';

  // <themes> generated by scripts/sync.mjs from zwipe's themes.css, don't edit by hand
const THEMES = {
  'rustbox-dark': ['#1c1210', '#f7bba1', '#a97f6d', '#c69580', '#72432f', '#341c12', '#482a1c', '#c44030', '#7a8a4a', '#c48030', '#8b2a1a', '#4a5a2a', '#8a5a18', '#5a9eaa', '#c45a6a', '#b8402a', '#61a5b1', '#ff919f', '#ea6d55', '#afc17e', '#cc8738', '#ff8873'],
  'rustbox-light': ['#f0dac5', '#3e1f17', '#804a32', '#623d28', '#c09060', '#e6c8a8', '#d4aa85', '#a03018', '#5a6a30', '#a06820', '#802010', '#404a20', '#805010', '#2a7a88', '#a03848', '#8a2818', '#00606e', '#710323', '#912f1f', '#334101', '#7c4700', '#760000'],
  'gruvbox-dark': ['#282828', '#ebdba2', '#a89984', '#c0b196', '#665c54', '#3c3836', '#504945', '#fb4934', '#b8bb26', '#fabd2f', '#cc241d', '#98971a', '#d79921', '#83a598', '#fabd2f', '#d3869b', '#83a598', '#fe8019', '#b8bb26', '#d3869b', '#fabd2f', '#8ec07c'],
  'gruvbox-light': ['#fbf1c7', '#32302f', '#6c6155', '#594f47', '#b09e88', '#f2e5bc', '#d5c4a1', '#9d0006', '#79740e', '#b57614', '#cc241d', '#98971a', '#d79921', '#076678', '#b57614', '#8f3f71', '#076678', '#af3a03', '#79740e', '#8f3f71', '#b57614', '#427b58'],
  'dracula-dark': ['#282a36', '#f8f8f2', '#9595a5', '#b5b5c0', '#5d6178', '#343746', '#44475a', '#ff6e6e', '#69ff94', '#ffffa5', '#ff5555', '#50fa7b', '#f1fa8c', '#ff79c6', '#ffb86c', '#bd93f9', '#8be9fd', '#ffb86c', '#50fa7b', '#bd93f9', '#f1fa8c', '#ff79c6'],
  'dracula-light': ['#f8f8f2', '#353748', '#626780', '#50536a', '#a8a89f', '#e8e8e2', '#c4c4ba', '#cc3333', '#1f9e3a', '#a88d10', '#ff5555', '#2dba4e', '#c4a616', '#a3144d', '#a34d14', '#846e15', '#036a96', '#a34d14', '#14710a', '#644ac9', '#846e15', '#a3144d'],
  'everforest-dark': ['#272e33', '#d3c6aa', '#9aa39a', '#aebab0', '#476a49', '#2e3b30', '#374a38', '#e67e80', '#a7c080', '#dbbc7f', '#c65c5e', '#87a060', '#bb9c5f', '#e67e80', '#a7c080', '#d699b6', '#7fbbb3', '#e69875', '#a7c080', '#d699b6', '#dbbc7f', '#83c092'],
  'everforest-light': ['#f3ead3', '#2a322d', '#5b6e5b', '#475347', '#89a580', '#c8d0b0', '#afbca2', '#f85552', '#8da101', '#dfa000', '#d83530', '#6d8100', '#bf8000', '#d96400', '#7b8e00', '#ca56a7', '#338ebe', '#d96400', '#7b8e00', '#ca56a7', '#b17400', '#18946a'],
  'catppuccin-dark': ['#1e1e2e', '#cdd6f4', '#8790b5', '#9da8d0', '#585b70', '#313244', '#45475a', '#f38ba8', '#a6e3a1', '#f9e2af', '#d36b88', '#86c381', '#d9c28f', '#cba6f7', '#94e2d5', '#fab387', '#89b4fa', '#fab387', '#a6e3a1', '#cba6f7', '#f9e2af', '#94e2d5'],
  'catppuccin-light': ['#eff1f5', '#313344', '#606376', '#4d5064', '#9ea2b1', '#d2d5db', '#bbbdc8', '#d20f39', '#40a02b', '#df8e1d', '#b20029', '#30800b', '#bf6e0d', '#8839ef', '#179299', '#f05600', '#1e66f5', '#f05600', '#399a23', '#8839ef', '#c47500', '#179299'],
  'tokyo-night-dark': ['#1a1b26', '#c0caf5', '#7f8dc0', '#9ba4cf', '#4b5277', '#24283b', '#383e5b', '#f7768e', '#9ece6a', '#e0af68', '#d7566e', '#7eae4a', '#c08f48', '#bb9af7', '#ff9e64', '#7aa2f7', '#7aa2f7', '#ff9e64', '#9ece6a', '#bb9af7', '#e0af68', '#7dcfff'],
  'tokyo-night-light': ['#d5d6db', '#1d2131', '#435186', '#3e414c', '#888e9f', '#babdc2', '#a4a8af', '#f52a65', '#587539', '#8c6c3e', '#d50a45', '#385519', '#6c4c1e', '#924dea', '#b15c00', '#2777e2', '#2777e2', '#b15c00', '#587539', '#924dea', '#8c6c3e', '#007197'],
  'nord-dark': ['#2e3440', '#eceff4', '#9ca8c2', '#b8c3d7', '#5c6881', '#3b4252', '#434c5e', '#bf616a', '#a3be8c', '#ebcb8b', '#9f414a', '#839e6c', '#cbab6b', '#81a1c1', '#88c0d0', '#b48ead', '#81a1c1', '#d08770', '#a3be8c', '#b48ead', '#ebcb8b', '#88c0d0'],
  'nord-light': ['#eceff4', '#2e3440', '#57637a', '#434c5e', '#97a1b5', '#cfd3db', '#b7bdc7', '#bf616a', '#a3be8c', '#ebcb8b', '#9f414a', '#839e6c', '#cbab6b', '#6989a8', '#578e9d', '#a17c9a', '#6989a8', '#bc755e', '#738c5c', '#a17c9a', '#9e8041', '#578e9d'],
  'rose-pine-dark': ['#191724', '#e0def4', '#8d88a6', '#a8a3c0', '#6e4a5e', '#2a2037', '#4d3548', '#eb6f92', '#9ccfd8', '#f6c177', '#cb4f72', '#7cafb8', '#d6a157', '#9ccfd8', '#f6c177', '#c4a7e7', '#31748f', '#f6c177', '#9ccfd8', '#c4a7e7', '#ebbcba', '#eb6f92'],
  'rose-pine-light': ['#faf4ed', '#544e76', '#666480', '#5e5780', '#d4899e', '#e6d5c7', '#e8c4d0', '#b4637a', '#56949f', '#ea9d34', '#94435a', '#36747f', '#ca7d14', '#56949f', '#c27800', '#907aa9', '#286983', '#c27800', '#56949f', '#907aa9', '#ca7672', '#b4637a'],
  'monokai-dark': ['#272822', '#f8f8f2', '#9b9a91', '#b5b2a8', '#605e4f', '#3a3937', '#4b4943', '#f92672', '#a6e22e', '#fd971f', '#d90652', '#86c20e', '#dd7700', '#f92672', '#e6db74', '#ae81ff', '#66d9ef', '#fd971f', '#a6e22e', '#ae81ff', '#e6db74', '#f92672'],
  'monokai-light': ['#fdf9f3', '#3b3930', '#6a6960', '#59564b', '#ada99a', '#dddcdb', '#c6c5bf', '#c4105a', '#6a9a10', '#c06a00', '#a40040', '#4a7a00', '#a05000', '#c4105a', '#9a8e1e', '#a274f1', '#1a9fb4', '#da7700', '#649a00', '#a274f1', '#9a8e1e', '#f92672'],
  'one-dark-dark': ['#282c34', '#abb2bf', '#8f96a3', '#99a0ac', '#5a616f', '#3c3e40', '#4b4d52', '#e06c75', '#98c379', '#e5c07b', '#c04c55', '#78a359', '#c5a05b', '#c678dd', '#61afef', '#e5c07b', '#61afef', '#d19a66', '#98c379', '#c678dd', '#e5c07b', '#56b6c2'],
  'one-dark-light': ['#fafafa', '#383a42', '#666971', '#525760', '#a4a9b4', '#dddddf', '#c4c5c9', '#e45649', '#50a14f', '#c18401', '#c33f34', '#30812f', '#a16400', '#a626a4', '#4078f2', '#c18401', '#4078f2', '#b76b01', '#50a14f', '#a626a4', '#cb7701', '#0184bc'],
  'solarized-dark': ['#002b36', '#d7dedf', '#909a9d', '#a7b3b6', '#4a6064', '#353a3b', '#414a4c', '#dc322f', '#859900', '#b58900', '#bc120f', '#657900', '#956900', '#cb4b16', '#b58900', '#2aa198', '#268bd2', '#cb4b16', '#859900', '#6c71c4', '#b58900', '#2aa198'],
  'solarized-light': ['#fdf6e3', '#3b382c', '#6a675c', '#595446', '#aca696', '#dadad7', '#c4c3bd', '#dc322f', '#859900', '#b58900', '#bc120f', '#657900', '#956900', '#cb4b16', '#af8300', '#209b92', '#268bd2', '#cb4b16', '#7f9300', '#6c71c4', '#af8300', '#209b92'],
  'ayu-dark': ['#0f1419', '#bfbdb6', '#7a818f', '#828a99', '#3d4149', '#1c2128', '#2a2f38', '#f07178', '#aad94c', '#ffb454', '#d95757', '#8ab33a', '#e6a33a', '#ff8f40', '#ffb454', '#d2a6ff', '#59c2ff', '#ff8f40', '#aad94c', '#d2a6ff', '#ffb454', '#95e6cb'],
  'ayu-light': ['#fcfcfc', '#5c6166', '#6b727b', '#6f7277', '#c8ccd0', '#ececed', '#dcdfe2', '#e65050', '#86b300', '#f2ae49', '#cc4040', '#6d9000', '#d99530', '#e57214', '#ca8400', '#a37acc', '#0097d9', '#e57214', '#74a000', '#a37acc', '#ca8400', '#229f7b'],
  'github-dark': ['#0d1117', '#c9d1d9', '#78808c', '#8b949e', '#30363d', '#21262d', '#262c34', '#f85149', '#3fb950', '#d29922', '#da3633', '#2ea043', '#bb8009', '#58a6ff', '#ab7df8', '#d29922', '#4493f8', '#db6d28', '#3fb950', '#ab7df8', '#d29922', '#07ace4'],
  'github-light': ['#ffffff', '#24292f', '#6c747e', '#57606a', '#d0d7de', '#eaeef2', '#dae0e6', '#cf222e', '#1a7f37', '#9a6700', '#a40e26', '#116329', '#7d4e00', '#0969da', '#8250df', '#bc4c00', '#0969da', '#bc4c00', '#1a7f37', '#8250df', '#9a6700', '#006a80'],
  'kanagawa-dark': ['#1f1f28', '#dcd7ba', '#8b8a81', '#a6a69c', '#54546d', '#2a2a37', '#363646', '#e82424', '#98bb6c', '#e6c384', '#c34043', '#7a9960', '#c9a86f', '#957fb8', '#7e9cd8', '#7aa89f', '#7e9cd8', '#ffa066', '#98bb6c', '#957fb8', '#e6c384', '#7aa89f'],
  'kanagawa-light': ['#f2ecbc', '#545464', '#686760', '#66666f', '#c9c093', '#e7e0ad', '#d9d1a0', '#c84053', '#6f894e', '#de9800', '#a8323f', '#5a7040', '#b87c00', '#624c83', '#4d699b', '#597b75', '#4d699b', '#cc6d00', '#6f894e', '#624c83', '#77713f', '#597b75'],
  'night-owl-dark': ['#011627', '#d6deeb', '#66859e', '#8badc1', '#1d3b53', '#0b2942', '#122d42', '#ef5350', '#addb67', '#ffeb95', '#c94a48', '#8fb851', '#d9c46f', '#c792ea', '#82aaff', '#ecc48d', '#82aaff', '#f78c6c', '#c5e478', '#c792ea', '#ecc48d', '#7fdbca'],
  'night-owl-light': ['#fbfbfb', '#403f53', '#5a7582', '#65727e', '#d0d0d9', '#efeff2', '#e0e0e6', '#d3423e', '#08916a', '#daaa01', '#b23430', '#077454', '#b88c00', '#994cc3', '#288ed7', '#4876d6', '#4876d6', '#c96765', '#08916a', '#994cc3', '#b98900', '#2aa298'],
  'vantablack-dark': ['#000000', '#f5f5f5', '#808080', '#b0b0b0', '#3a3a3a', '#141414', '#242424', '#c05a5a', '#6a9a6a', '#b09050', '#8a3a3a', '#4a6a4a', '#7a6030', '#e0e0e0', '#909090', '#b8b8b8', '#8d8d8d', '#b9b9b9', '#a4a4a4', '#cecece', '#9b9b9b', '#b0b0b0'],
  'vantablack-light': ['#ffffff', '#0a0a0a', '#737373', '#4a4a4a', '#c4c4c4', '#ededed', '#dadada', '#a83232', '#3a6a3a', '#8a6a20', '#822020', '#2a4a2a', '#6a5010', '#1a1a1a', '#6a6a6a', '#3a3a3a', '#8d8d8d', '#949494', '#929292', '#8f8f8f', '#8f8f8f', '#919191'],
  'vscode-dark': ['#1e1e1e', '#d4d4d4', '#888888', '#a0a0a0', '#3c3c3c', '#252526', '#2d2d2d', '#f14c4c', '#4ec9b0', '#cca700', '#c93c3c', '#3ba892', '#a88a00', '#c586c0', '#569cd6', '#6a9955', '#569cd6', '#ce9178', '#6a9955', '#c586c0', '#dcdcaa', '#4ec9b0'],
  'vscode-light': ['#ffffff', '#1e1e1e', '#737373', '#4a4a4a', '#c8c8c8', '#ededed', '#dcdcdc', '#cd3131', '#098658', '#bf8803', '#a82525', '#076e48', '#9c7002', '#af00db', '#0070c1', '#098658', '#0070c1', '#795e26', '#098658', '#af00db', '#a31515', '#267f99'],
  'zenburn-dark': ['#3f3f3f', '#dcdccc', '#aeaea4', '#b5b5a5', '#6f6f6f', '#4a4a4a', '#5a5a5a', '#cc9393', '#7f9f7f', '#f0dfaf', '#a86a6a', '#5f7f5f', '#c0b080', '#f0dfaf', '#dfaf8f', '#7f9f7f', '#8cd0d3', '#dfaf8f', '#7f9f7f', '#dc8cc3', '#f0dfaf', '#93e0e3'],
  'zenburn-light': ['#e8e6d8', '#3f3f38', '#656556', '#5c5c50', '#bdbba8', '#dedcce', '#cecab8', '#9a5a5a', '#5a7a5a', '#9a7a3a', '#7a4444', '#456045', '#7a5e28', '#908154', '#a57859', '#678768', '#488b8e', '#a57859', '#678768', '#b4689d', '#908154', '#408d91'],
  'ethereal-dark': ['#1b1d29', '#d8dbf0', '#8387a1', '#a6aacb', '#3a3e58', '#232634', '#2e3145', '#e08aa8', '#9ad0b0', '#e0c48a', '#bf6f8c', '#78ab8f', '#bfa46f', '#c89dc1', '#7d82d9', '#92a593', '#7d82d9', '#eb8b54', '#92a593', '#c89dc1', '#e9bb4f', '#a3bfd1'],
  'ethereal-light': ['#f4f5fb', '#3a3d55', '#676c8b', '#63667e', '#ccd0e4', '#e8eaf4', '#dadeed', '#c06585', '#5a9a78', '#b08a45', '#a04d6c', '#46805e', '#8e6c2f', '#a87fa1', '#7d82d9', '#809381', '#7d82d9', '#d0723a', '#809381', '#a87fa1', '#af8200', '#738d9e'],
  'hackerman-dark': ['#050805', '#33ff33', '#208e20', '#2ccc2c', '#196619', '#0c1f0c', '#123312', '#ff5555', '#33ff33', '#aaff33', '#cc3333', '#22aa22', '#7fbf1f', '#829dd4', '#50f872', '#50f7d4', '#829dd4', '#50f7a3', '#50f872', '#86a7df', '#50f7d4', '#7cf8f7'],
  'hackerman-light': ['#e6f2e6', '#0a3a0a', '#477447', '#2c5c2c', '#a8c8a8', '#d2e4d2', '#c0d8c0', '#b03030', '#1a7a1a', '#6a8a10', '#8a2020', '#145c14', '#526c0c', '#6a84ba', '#009b00', '#009b7d', '#6a84ba', '#009b4e', '#009b00', '#6888be', '#009b7d', '#009797'],
  'matte-black-dark': ['#121212', '#e8e8e8', '#808080', '#9a9a9a', '#2e2e2e', '#1c1c1c', '#262626', '#b05a50', '#7e8f5a', '#d4a35a', '#8a453e', '#5f6d42', '#a87e3f', '#e68e0d', '#c02523', '#ffc107', '#bebebe', '#e68e0d', '#ffc107', '#c63d3d', '#d35f5f', '#c02523'],
  'matte-black-light': ['#efefef', '#161616', '#6a6a6a', '#444444', '#cccccc', '#e2e2e2', '#d6d6d6', '#9a463c', '#5f6d42', '#9a742a', '#7a352c', '#465030', '#7a5a1e', '#cb7500', '#b91c1c', '#b67b00', '#868686', '#cb7500', '#b67b00', '#c63d3d', '#d35f5f', '#b91c1c'],
  'miasma-dark': ['#222222', '#c2c2b0', '#8d8d80', '#9a9a8a', '#4a4a40', '#2c2c28', '#3a3a34', '#c98a6a', '#78834b', '#bb9457', '#a86a4a', '#5c6638', '#98763f', '#5f875f', '#78824b', '#7f6e58', '#78824b', '#b36d43', '#5f875f', '#bb7744', '#c9a554', '#7f6e58'],
  'miasma-light': ['#e6e2d4', '#33332a', '#636354', '#52524a', '#bab6a2', '#dcd8c8', '#ccc8b6', '#9a5a3a', '#5c6638', '#8a6a30', '#7a4428', '#464e28', '#6c5220', '#5f875f', '#78824b', '#685742', '#78824b', '#b36d43', '#5f875f', '#b4713e', '#9d7a24', '#685742'],
  'osaka-jade-dark': ['#111c18', '#c1cec4', '#76897f', '#97a89e', '#33453d', '#1a2621', '#26332d', '#cf5a5a', '#7ab585', '#d4b26a', '#a84545', '#5c9666', '#b0904a', '#2dd5b7', '#509475', '#d4b26a', '#509475', '#a2734b', '#549e6a', '#d2689c', '#e5c736', '#2dd5b7'],
  'osaka-jade-light': ['#e8efe8', '#24332c', '#5c6c63', '#455249', '#b4c6ba', '#d8e4da', '#c6d4c8', '#a84545', '#3a7a54', '#8a6a2a', '#863434', '#2c603f', '#6c521e', '#00957a', '#509475', '#8a6a2a', '#509475', '#a2734b', '#48925e', '#cb6296', '#9f8100', '#00957a'],
  'ristretto-dark': ['#2c2525', '#fff1f3', '#988e8f', '#c3b7b8', '#5b5152', '#362e2e', '#453b3b', '#fd6883', '#adda78', '#f9cc6c', '#d1546c', '#8fb85f', '#d1aa54', '#fd6883', '#f38d70', '#85dacc', '#85dacc', '#fb9a77', '#adda78', '#a8a9eb', '#f9cc6c', '#f38d70'],
  'ristretto-light': ['#f5ece9', '#43383a', '#736668', '#5e5254', '#cbb9b6', '#e8dcd8', '#d8c8c4', '#c33f5a', '#6f9440', '#b08a2a', '#a02c46', '#587733', '#8e6c1e', '#c33f5a', '#ca684c', '#3d9488', '#3d9488', '#cb6f4d', '#6a9431', '#7e7ebd', '#ab800e', '#ca684c'],
  'synthwave-84-dark': ['#262335', '#f5eeff', '#848bbd', '#b6a8d8', '#453a63', '#2d283e', '#37324d', '#fe4450', '#72f1b8', '#fede5d', '#d43442', '#4fc793', '#d4bb45', '#ff7edb', '#ff8b39', '#0080ff', '#0080ff', '#fe5442', '#03edf9', '#9b27ff', '#f3e70f', '#ff7edb'],
  'synthwave-84-light': ['#f5eefb', '#2d2340', '#706589', '#574a70', '#cabce0', '#e6ddf2', '#d8cce8', '#d1204a', '#1f9a6a', '#b07a10', '#a81840', '#167a52', '#8e6208', '#c31d86', '#d1621a', '#0080ff', '#0080ff', '#f74d3c', '#0098a5', '#8f00ff', '#9a8c00', '#d557b4'],
  'powershell-dark': ['#012456', '#eeedf0', '#8fa0c4', '#b3bed4', '#274b7d', '#082a5c', '#16386c', '#ff6b6b', '#4ec94e', '#ffe14a', '#d44444', '#3ba33b', '#d4bb3a', '#00ff00', '#00ffff', '#808000', '#1761ff', '#808000', '#00ff00', '#ff00ff', '#ffff00', '#00ffff'],
  'powershell-light': ['#f2f4f8', '#012456', '#5a6b8c', '#364c72', '#b4c0d8', '#e0e6f0', '#ccd6e6', '#c42b1c', '#2a8a2a', '#9a7a00', '#a02216', '#206e20', '#7a6000', '#000080', '#008080', '#008000', '#000080', '#800000', '#008000', '#800080', '#808000', '#008080'],
  'docs-rs-dark': ['#353535', '#dddddd', '#a1a1a1', '#bcbcbc', '#5a5a5a', '#2a2a2a', '#454545', '#e05d44', '#97b84f', '#d2991d', '#b8492f', '#6f8f38', '#a87814', '#ab8ac1', '#d2991d', '#83a300', '#769acb', '#d97f26', '#83a300', '#ab8ac1', '#d2991d', '#3e999f'],
  'docs-rs-light': ['#f9f7ec', '#2a2a2a', '#6e6a5c', '#4c4a40', '#cfc9b0', '#ece8d6', '#ddd8c2', '#c0392b', '#5f7a2e', '#a8760f', '#9c2c20', '#4a601f', '#86600a', '#8959a8', '#4271ae', '#b76514', '#4271ae', '#b76514', '#718c00', '#8959a8', '#de6d00', '#3e999f'],
  'protanopia-dark': ['#1e1e22', '#d6d1d1', '#958f8f', '#ada7a7', '#5c5454', '#343232', '#454141', '#5b8bd4', '#d4a830', '#e8973a', '#3b6bb4', '#b48810', '#c8771a', '#d4a830', '#5b8bd4', '#e8973a', '#ffd97c', '#ade0ff', '#d2ac4e', '#81b2fd', '#a58118', '#5886ce'],
  'protanopia-light': ['#f2f0ed', '#383232', '#686262', '#564f4f', '#a99f9f', '#d6d4d4', '#c0bdbd', '#2e5ea0', '#8a7010', '#b06a10', '#1e4e90', '#6a5000', '#904a00', '#8a7010', '#2e5ea0', '#b06a10', '#432800', '#002a68', '#6b4e00', '#215193', '#947700', '#497bc0'],
  'deuteranopia-dark': ['#1e1f24', '#d1d4d8', '#8f9297', '#a6aab1', '#525760', '#323334', '#414246', '#e07040', '#5090d0', '#d4b840', '#c05020', '#3070b0', '#b49820', '#5090d0', '#e07040', '#d4b840', '#a0e4ff', '#f6de7d', '#74b6fa', '#c8b04f', '#488acb', '#9c851a'],
  'deuteranopia-light': ['#f0f0f4', '#313339', '#616369', '#4e5158', '#9da2ac', '#d4d4d6', '#bcbec1', '#b04820', '#2860a0', '#a08810', '#902800', '#184080', '#806800', '#2860a0', '#b04820', '#a08810', '#002b67', '#402a00', '#195392', '#675000', '#447cbf', '#907900'],
  'tritanopia-dark': ['#22201e', '#d8d3d2', '#98918f', '#b0a8a6', '#5f5551', '#353333', '#474241', '#d45060', '#40b0a0', '#d08040', '#b43040', '#209080', '#b06020', '#40b0a0', '#d45060', '#d08040', '#75f8e4', '#ffbdc2', '#3fcab7', '#f39097', '#009d8c', '#c4656d'],
  'tritanopia-light': ['#f2efe8', '#38312f', '#686260', '#564f4c', '#aa9f9b', '#d5d3d2', '#bfbcba', '#a02030', '#207060', '#a06020', '#801020', '#105040', '#804010', '#207060', '#a02030', '#a06020', '#003f2c', '#5c0012', '#006751', '#883136', '#009178', '#b65a5c'],
  'achromatopsia-dark': ['#1a1a1a', '#f0f0f0', '#8a8a8a', '#b8b8b8', '#4a4a4a', '#2a2a2a', '#383838', '#e8e8e8', '#9a9a9a', '#c2c2c2', '#b0b0b0', '#6a6a6a', '#8a8a8a', '#d8d8d8', '#909090', '#b0b0b0', '#f5f5f5', '#838383', '#d7d7d7', '#696969', '#bababa', '#9e9e9e'],
  'achromatopsia-light': ['#f2f2f2', '#141414', '#6b6b6b', '#444444', '#b8b8b8', '#e0e0e0', '#cecece', '#202020', '#707070', '#484848', '#404040', '#888888', '#606060', '#2a2a2a', '#808080', '#505050', '#060606', '#454545', '#181818', '#5d5d5d', '#2e2e2e', '#777777'],
};
// </themes>

  // <core> copied by scripts/sync.mjs from src/core.js, don't edit by hand
  // What every orangui userscript shares: the theme as variables, the theme picker, and the Tampermonkey menu.
  // scripts/sync.mjs copies this file into each *.user.js between the core markers. A site's own code runs after it and calls start().

  // The order of a theme's colors in THEMES. Keep in step with KEYS in scripts/sync.mjs.
  const KEYS = [
    'bg', 'text', 'muted', 'subtle',
    'b1', 'b2', 'b3',
    'err', 'ok', 'warn',
    'berr', 'bok', 'bwarn',
    'a1', 'a2', 'a3',
    'p1', 'p2', 'p3', 'p4', 'p5', 'p6',
  ];

  // == theme names, as zwipe-core's display_theme_name spells them ==

  const COLORBLIND = ['protanopia', 'deuteranopia', 'tritanopia', 'achromatopsia'];
  const SPELLED = {
    'rose-pine': 'Rosé Pine',
    vscode: 'VS Code',
    github: 'GitHub',
    'synthwave-84': "Synthwave '84",
    powershell: 'PowerShell',
    'docs-rs': 'docs.rs',
  };
  const label = (slug) => SPELLED[slug] ?? slug.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
  const SLUGS = [...new Set(Object.keys(THEMES).map((k) => k.replace(/-(dark|light)$/, '')))].sort();
  const REGULAR = SLUGS.filter((s) => !COLORBLIND.includes(s));
  const DEFAULT = { name: 'gruvbox', dark: true };

  const FONT = "'JetBrains Mono', 'JetBrainsMono Nerd Font', 'JetBrainsMono NF', monospace";
  const TOP = window.top === window;

  const v = (k) => `var(--og-${k})`;
  const mix = (c, pct, base = v('bg')) => `color-mix(in srgb, ${c} ${pct}%, ${base})`;
  const clear = (c, pct) => `color-mix(in srgb, ${c} ${pct}%, transparent)`;

  // == stored state, shared by every site and tab the scripts run on ==

  const valid = (t) => (t && THEMES[`${t.name}-${t.dark ? 'dark' : 'light'}`] ? t : DEFAULT);
  let current = valid(GM_getValue('theme', DEFAULT));
  let enabled = GM_getValue('enabled', true);
  let showLauncher = GM_getValue('launcher', true);
  const spotKey = `launcher@${location.hostname}`;
  const HOME = { right: 12, bottom: 12 };
  let picker = null;
  let onEnabled = () => {};
  // Run after every theme swap, for anything that copies the theme somewhere the root variables don't reach.
  const onTheme = [];

  // == the theme as variables: zwipe's names, prefixed so a page can't collide with them ==

  function themeCss({ name, dark }) {
    const colors = THEMES[`${name}-${dark ? 'dark' : 'light'}`];
    const vars = KEYS.map((k, i) => `--og-${k}: ${colors[i]};`).join(' ');
    // zwipe's sink: the content area sits darker than the chrome on a dark theme, brighter on a light one.
    const derived = dark
      ? '--og-sink: color-mix(in srgb, var(--og-bg), #000 15%); --og-overlay: rgba(0,0,0,.6); --og-shadow-sm: 0 4px 12px rgba(0,0,0,.3); --og-shadow-md: 0 4px 12px rgba(0,0,0,.5);'
      : '--og-sink: color-mix(in srgb, var(--og-bg), #fff 35%); --og-overlay: rgba(0,0,0,.3); --og-shadow-sm: 0 4px 12px rgba(0,0,0,.1); --og-shadow-md: 0 4px 12px rgba(0,0,0,.15);';
    return `:root { ${vars} ${derived} color-scheme: ${dark ? 'dark' : 'light'}; }`;
  }

  // Rounds the selected elements into zwipe's squircle, or a rounded square where the browser has no corner-shape.
  const squircle = (selector) => `
    :is(${selector}) { border-radius: 30% !important; }
    @supports (corner-shape: squircle) { :is(${selector}) { border-radius: 50% !important; corner-shape: squircle; } }
  `;

  // zwipe's sunken content area: the sink color under a faint 28px grid that holds still while the content scrolls over it.
  const grid = (selector) => `
    :is(${selector}) {
      background-color: var(--og-sink) !important;
      background-image:
        linear-gradient(color-mix(in srgb, var(--og-text) 4%, transparent) 1px, transparent 1px),
        linear-gradient(90deg, color-mix(in srgb, var(--og-text) 4%, transparent) 1px, transparent 1px) !important;
      background-size: 28px 28px !important;
    }
  `;

  const CORE_CSS = `
    input, textarea, [contenteditable] { caret-color: var(--og-a2); }
    ::selection { background: var(--og-a2); color: var(--og-bg); }
    * { scrollbar-width: thin; scrollbar-color: var(--og-b1) transparent; }

    /* zwipe's theme wipe: the new theme sweeps across, right to left when going light to dark */
    html[data-og-wipe]::view-transition-old(root), html[data-og-wipe]::view-transition-new(root) {
      animation: none; mix-blend-mode: normal;
    }
    html[data-og-wipe]::view-transition-new(root) { animation: og-wipe .4s cubic-bezier(.65, 0, .35, 1); }
    html[data-og-wipe="left"]::view-transition-new(root) { animation-name: og-wipe-left; }
    @keyframes og-wipe { from { clip-path: inset(0 100% 0 0); } to { clip-path: inset(0); } }
    @keyframes og-wipe-left { from { clip-path: inset(0 0 0 100%); } to { clip-path: inset(0); } }
  `;

  const baseStyle = document.createElement('style');
  baseStyle.dataset.orangui = 'base';
  const themeStyle = document.createElement('style');
  themeStyle.dataset.orangui = 'theme';

  // Swaps the theme in, inside zwipe's wipe when asked for and the browser can run it.
  function apply(theme, wipe = false) {
    const leaving = current;
    current = theme;
    // Writes whatever is current when it runs, as a fast run of picks can land their swaps out of order.
    const swap = () => {
      themeStyle.textContent = themeCss(current);
      for (const hook of onTheme) hook();
    };
    const still = matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (!wipe || !enabled || still || !document.startViewTransition) return swap();
    const root = document.documentElement;
    root.dataset.ogWipe = theme.dark && !leaving.dark ? 'left' : 'right';
    document.startViewTransition(swap).finished.finally(() => delete root.dataset.ogWipe);
  }

  function setEnabled(on) {
    enabled = on;
    if (on) document.documentElement.append(baseStyle, themeStyle);
    else { baseStyle.remove(); themeStyle.remove(); }
    onEnabled(on);
    picker?.sync();
  }

  // == the picker: zwipe's ThemeSheet, in a shadow root so the page's CSS can't reach it ==

  const h = (tag, props = {}, ...kids) => {
    const el = document.createElement(tag);
    for (const [k, val] of Object.entries(props)) {
      if (k.startsWith('on')) el.addEventListener(k.slice(2), val);
      else if (k === 'style') el.style.cssText = val;
      else if (val !== false && val != null) el.setAttribute(k, val === true ? '' : val);
    }
    el.append(...kids.flat());
    return el;
  };

  const PICKER_CSS = `
    :host { all: initial; }
    * { box-sizing: border-box; font-family: ${FONT}; }

    .launcher {
      position: fixed; z-index: 2147483646; width: 1.6rem; height: 1.6rem; padding: 0;
      display: grid; place-items: center; touch-action: none; user-select: none;
      background: var(--og-bg); color: var(--og-text); border: 1px solid var(--og-b1); border-radius: .5rem;
      box-shadow: var(--og-shadow-sm); font-size: .9rem; line-height: 1; cursor: grab; opacity: .3;
      transition: opacity .2s, border-color .2s, color .2s;
    }
    .launcher:hover, .launcher:focus-visible { opacity: 1; border-color: var(--og-a1); color: var(--og-a1); outline: none; }
    .launcher.dragging { cursor: grabbing; opacity: 1; }

    .backdrop { position: fixed; inset: 0; z-index: 2147483646; background: var(--og-overlay); }
    .sheet {
      position: fixed; z-index: 2147483647; left: 50%; top: 50%;
      width: min(60rem, calc(100vw - 2rem)); max-height: min(48rem, calc(100vh - 2rem));
      display: flex; flex-direction: column; overflow: hidden;
      background: var(--og-bg); color: var(--og-text);
      border: 1px solid var(--og-b2); border-radius: 1rem; box-shadow: var(--og-shadow-md);
    }
    .modal-header {
      position: relative; display: flex; justify-content: center; align-items: center; flex-shrink: 0;
      padding: 1.5rem 2rem; border-bottom: 1px solid var(--og-b2); cursor: grab; touch-action: none; user-select: none;
    }
    .modal-header.dragging { cursor: grabbing; }
    .modal-title { font-size: 1.3rem; color: var(--og-a3); letter-spacing: .05em; }
    .mode { position: absolute; right: 1.5rem; }

    .chip {
      padding: .45rem .9rem; border: 1px solid var(--og-b1); border-radius: .6rem; font-size: .95rem;
      color: var(--og-text); background: var(--og-bg); box-shadow: var(--og-shadow-sm); cursor: pointer;
      transition: all .2s ease;
    }
    .chip:hover, .chip:focus-visible { border-color: var(--og-a2); color: var(--og-a2); outline: none; }

    /* the themes as a grid of cards, as many across as the width allows */
    .modal-content {
      padding: 1.5rem 2rem; overflow-y: auto; flex: 1; scrollbar-width: none;
      display: grid; grid-template-columns: repeat(auto-fill, minmax(16rem, 1fr)); gap: .6rem; align-content: start;
    }
    .pref-row {
      display: flex; align-items: center; justify-content: space-between; gap: .5rem; width: 100%;
      padding: .9rem 1.1rem; background: var(--og-bg); border: 1px solid var(--og-b1); border-radius: .6rem;
      color: var(--og-muted); font-size: 1rem; text-align: left; cursor: pointer;
      transition: border-color .15s, color .15s;
    }
    .pref-row:hover, .pref-row:focus-visible { color: var(--og-text); outline: none; }
    .pref-row.selected { border-color: var(--og-a2); color: var(--og-text); }
    .pref-row > span:first-child { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .theme-swatches {
      display: flex; align-items: center; gap: .25rem; flex-shrink: 0; padding: .3rem .35rem;
      border-radius: .45rem; background: var(--s-bg); border: 1px solid var(--s-muted);
    }
    .theme-dot { width: .95rem; height: .95rem; border-radius: .3rem; flex-shrink: 0; }
    .pref-section-label { grid-column: 1 / -1; font-size: 1.15rem; color: var(--og-a1); letter-spacing: .1em; text-align: center; margin: 1rem 0 .4rem; }

    .util-bar {
      flex-shrink: 0; display: flex; justify-content: center; align-items: center; gap: .5rem;
      padding: 1.25rem; border-top: 1px solid var(--og-b2);
    }
    .util-btn {
      padding: .55rem 1.3rem; font-size: 1rem; border-radius: .5rem; background: var(--og-bg);
      border: 1px solid var(--og-b1); color: var(--og-text); cursor: pointer; transition: all .1s ease;
    }
    .util-btn:hover:not(:disabled) { border-color: var(--og-a1); color: var(--og-a1); }
    .util-btn:disabled { opacity: .5; cursor: not-allowed; }
    .hint { font-size: .85rem; color: var(--og-warn); text-align: center; padding: 0 1rem 1rem; }
    .hint:empty { display: none; }
  `;

  // Hands the pointer's travel to onMove once it passes a few pixels. A press that stays put is a click.
  function draggable(handle, onMove, onDrop) {
    handle.addEventListener('pointerdown', (e) => {
      if (e.button !== 0 || e.target.closest('button:not(.launcher)')) return;
      const start = { x: e.clientX, y: e.clientY };
      let moved = false;
      handle.setPointerCapture(e.pointerId);
      const move = (m) => {
        const dx = m.clientX - start.x;
        const dy = m.clientY - start.y;
        if (!moved && Math.hypot(dx, dy) < 4) return;
        moved = true;
        handle.classList.add('dragging');
        onMove(m, dx, dy);
      };
      const up = () => {
        handle.removeEventListener('pointermove', move);
        handle.classList.remove('dragging');
        if (moved) {
          onDrop?.();
          // Swallows the click that ends a drag.
          handle.addEventListener('click', (c) => { c.stopPropagation(); c.preventDefault(); }, { capture: true, once: true });
        }
      };
      handle.addEventListener('pointermove', move);
      handle.addEventListener('pointerup', up, { once: true });
      handle.addEventListener('pointercancel', up, { once: true });
    });
  }

  function makePicker() {
    const host = h('orangui-picker');
    const shadow = host.attachShadow({ mode: 'closed' });
    const style = h('style');
    style.textContent = PICKER_CSS;

    // The launcher keeps its spot per site, as distances from the right and bottom edges.
    let spot = GM_getValue(spotKey, HOME);
    const launcher = h('button', { class: 'launcher', title: 'orangui themes (Alt+Shift+T)', 'aria-label': 'Themes' }, '◐');
    const place = () => {
      const max = (n, room) => Math.min(Math.max(n, 0), Math.max(room - 26, 0));
      launcher.style.right = `${max(spot.right, innerWidth)}px`;
      launcher.style.bottom = `${max(spot.bottom, innerHeight)}px`;
    };
    let from;
    launcher.addEventListener('pointerdown', () => { from = { ...spot }; });
    draggable(
      launcher,
      (_e, dx, dy) => { spot = { right: from.right - dx, bottom: from.bottom - dy }; place(); },
      () => {
        spot = { right: parseFloat(launcher.style.right), bottom: parseFloat(launcher.style.bottom) };
        GM_setValue(spotKey, spot);
      },
    );
    launcher.addEventListener('click', () => open());
    addEventListener('resize', place);
    place();

    const backdrop = h('div', { class: 'backdrop', onclick: () => back() });
    const title = h('div', { class: 'modal-title', id: 'og-title' }, 'Themes');
    const mode = h('button', { class: 'chip mode', title: 'Dark or light (← →)', onclick: () => flip() });
    const header = h('div', { class: 'modal-header' }, title, mode);
    const list = h('div', { class: 'modal-content' });
    const save = h('button', { class: 'util-btn', onclick: () => keep() }, 'Save');
    const hint = h('div', { class: 'hint' });
    const sheet = h(
      'div',
      { class: 'sheet', role: 'dialog', 'aria-modal': 'true', 'aria-labelledby': 'og-title' },
      header,
      list,
      h('div', { class: 'util-bar' }, h('button', { class: 'util-btn', onclick: () => back() }, 'Back'), save),
      hint,
    );

    // The sheet's offset from center, kept while the page stays open.
    let offset = { x: 0, y: 0 };
    let grab;
    const position = () => { sheet.style.transform = `translate(calc(-50% + ${offset.x}px), calc(-50% + ${offset.y}px))`; };
    header.addEventListener('pointerdown', () => { grab = { ...offset }; });
    draggable(header, (_e, dx, dy) => { offset = { x: grab.x + dx, y: grab.y + dy }; position(); });
    position();

    let original = null;
    let returnFocus = null;
    const isOpen = () => original !== null;
    const same = (a, b) => a.name === b.name && a.dark === b.dark;

    const row = (slug, dark) => {
      const colors = THEMES[`${slug}-${dark ? 'dark' : 'light'}`];
      const at = (k) => colors[KEYS.indexOf(k)];
      const selected = current.name === slug;
      return h(
        'button',
        { class: selected ? 'pref-row selected' : 'pref-row', 'aria-pressed': String(selected), onclick: () => pick({ name: slug, dark }) },
        h('span', {}, label(slug)),
        h(
          'span',
          { class: 'theme-swatches', style: `--s-bg: ${at('bg')}; --s-muted: ${at('muted')}` },
          ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'].map((k) => h('span', { class: 'theme-dot', style: `background: ${at(k)}` })),
        ),
      );
    };

    // The picker's order: the regular themes, then the colorblind ones under their own label.
    const ORDER = [...REGULAR, ...COLORBLIND.filter((s) => SLUGS.includes(s))];

    function render() {
      const { dark } = current;
      mode.textContent = dark ? '☾ dark' : '☀ light';
      mode.setAttribute('aria-pressed', String(dark));
      list.replaceChildren(
        ...REGULAR.map((s) => row(s, dark)),
        h('div', { class: 'pref-section-label' }, 'Colorblind'),
        ...ORDER.slice(REGULAR.length).map((s) => row(s, dark)),
      );
      save.disabled = same(current, original);
    }

    // A held arrow key skips the wipe, so a fast run through the list doesn't queue up sweeps.
    function pick(theme, wipe = true) {
      if (same(theme, current)) return;
      apply(theme, wipe);
      render();
      const selected = list.querySelector('.selected');
      selected?.focus({ preventScroll: true });
      selected?.scrollIntoView({ block: 'nearest' });
    }

    const flip = (wipe = true) => pick({ ...current, dark: !current.dark }, wipe);
    const jump = (to, wipe = true) => pick({ ...current, name: ORDER[(to + ORDER.length) % ORDER.length] }, wipe);
    const at = () => ORDER.indexOf(current.name);

    function open() {
      if (isOpen()) return;
      if (!enabled) setEnabled(true);
      original = current;
      returnFocus = document.activeElement;
      // Dark Reader rewrites the same colors, and the two fight.
      hint.textContent = document.documentElement.hasAttribute('data-darkreader-mode')
        ? 'Dark Reader is on here. Turn it off for this site so the themes come through.'
        : '';
      render();
      shadow.append(backdrop, sheet);
      launcher.remove();
      (list.querySelector('.selected') ?? list.firstElementChild)?.focus({ preventScroll: true });
      list.querySelector('.selected')?.scrollIntoView({ block: 'center' });
    }

    function close() {
      original = null;
      backdrop.remove();
      sheet.remove();
      sync();
      returnFocus?.focus?.();
    }

    function back() {
      if (!isOpen()) return;
      if (!same(current, original)) apply(original, true);
      close();
    }

    function keep() {
      GM_setValue('theme', current);
      close();
    }

    function sync() {
      if (showLauncher && enabled && !isOpen()) shadow.append(launcher);
      else launcher.remove();
    }

    function home() {
      spot = HOME;
      GM_setValue(spotKey, spot);
      place();
    }

    // Capture phase, so the page never sees the keys the picker answers.
    addEventListener('keydown', (e) => {
      const toggle = e.altKey && e.shiftKey && !e.ctrlKey && !e.metaKey && e.code === 'KeyT';
      const plain = !e.altKey && !e.ctrlKey && !e.metaKey;
      const keys = {
        Escape: () => back(),
        Enter: () => (save.disabled ? close() : keep()),
        ArrowDown: () => jump(at() + 1, !e.repeat),
        ArrowUp: () => jump(at() - 1, !e.repeat),
        Home: () => jump(0),
        End: () => jump(-1),
        ArrowLeft: () => flip(!e.repeat),
        ArrowRight: () => flip(!e.repeat),
      };
      if (!toggle && !(isOpen() && plain && keys[e.key])) return;
      e.preventDefault();
      e.stopPropagation();
      if (toggle) isOpen() ? back() : open();
      else keys[e.key]();
    }, true);

    shadow.append(style);
    sync();
    const mount = () => document.documentElement.append(host);
    if (document.readyState === 'loading') addEventListener('DOMContentLoaded', mount, { once: true });
    else mount();

    return { open, isOpen, sync, home };
  }

  // == the recolor: color literals in a page's stylesheets and inline styles, sent to the nearest theme color ==

  // Each literal is read as the light app it was written for and swapped for a theme variable, so a theme change needs no second pass.
  // A site that themes its grays some other way (Fluent's tokens) asks for the saturated colors only.

  const COLOR = /#[0-9a-f]{3,8}\b|rgba?\([^)]*\)|\b(?:white|black)\b/gi;

  function parse(text) {
    const t = text.toLowerCase();
    if (t === 'white') return { r: 255, g: 255, b: 255, a: 1 };
    if (t === 'black') return { r: 0, g: 0, b: 0, a: 1 };
    if (t[0] === '#') {
      let hex = t.slice(1);
      if (hex.length <= 4) hex = [...hex].map((c) => c + c).join('');
      if (hex.length !== 6 && hex.length !== 8) return null;
      const n = (i) => parseInt(hex.slice(i, i + 2), 16);
      return { r: n(0), g: n(2), b: n(4), a: hex.length === 8 ? n(6) / 255 : 1 };
    }
    const parts = t.match(/[\d.]+%?/g);
    if (!parts || parts.length < 3) return null;
    const alpha = parts[3] === undefined ? 1 : parts[3].endsWith('%') ? parseFloat(parts[3]) / 100 : parseFloat(parts[3]);
    return { r: +parts[0], g: +parts[1], b: +parts[2], a: alpha };
  }

  // Hue in degrees, HSL saturation and lightness 0 to 1, and the lightness over white, as the light app would show it.
  function measure({ r, g, b, a }) {
    const [R, G, B] = [r / 255, g / 255, b / 255];
    const max = Math.max(R, G, B);
    const min = Math.min(R, G, B);
    const l = (max + min) / 2;
    const d = max - min;
    const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1));
    let hue = 0;
    if (d) hue = max === R ? ((G - B) / d) % 6 : max === G ? (B - R) / d + 2 : (R - G) / d + 4;
    return { hue: (hue * 60 + 360) % 360, s, l, over: l * a + (1 - a), under: l * a };
  }

  const hueColor = (hue) =>
    hue < 15 || hue >= 335 ? 'err' : hue < 40 ? 'p2' : hue < 70 ? 'warn' : hue < 160 ? 'ok' : hue < 190 ? 'p6' : hue < 255 ? 'a1' : 'p4';

  // Returns the theme expression for one color literal in a property of the given role, or null to leave it alone.
  // `dark` says the color was written for a dark page, where the gray ladder runs the other way.
  function recolor(text, role, neutrals, dark) {
    const c = parse(text);
    if (!c || c.a === 0) return null;
    const { hue, s, l, over, under } = measure(c);
    const neutral = s < 0.18 || l > 0.94 || l < 0.08;
    if (neutral && !neutrals) return null;

    if (role === 'shadow') return neutral ? null : clear(v(hueColor(hue)), Math.round(c.a * 100));

    if (!neutral) {
      const theme = v(hueColor(hue));
      if (role !== 'bg') return c.a < 1 ? clear(theme, Math.round(c.a * 100)) : theme;
      // zwipe never fills with a full accent: a tint of it, pastels fainter still.
      const tint = mix(theme, l > 0.85 ? 12 : 22);
      return c.a < 0.5 ? clear(theme, Math.round(c.a * 40)) : tint;
    }

    if (dark) return darkGray(c, role, l, under);

    if (role === 'bg') {
      // A dim black wash is a modal backdrop or a shadow layer, and stays one.
      if (l < 0.2 && c.a >= 0.3 && c.a < 0.95) return null;
      if (over >= 0.985) return c.a < 1 ? clear(v('bg'), Math.round(c.a * 100)) : v('bg');
      if (over >= 0.93) return v('sink');
      if (over >= 0.7) return v('b2');
      if (over >= 0.3) return v('b1');
      return v('b2');
    }
    if (role === 'border') return over >= 0.75 ? v('b2') : v('b1');
    // Text: near black and near white are both body text, the grays between them step down.
    if (over < 0.3 || over > 0.85) return v('text');
    if (over < 0.45) return v('subtle');
    return v('muted');
  }

  // A gray from a dark page, by its lightness over black: Halo's dark theme is about 21% for the page, 26% for panels, 32% for raised and hover.
  function darkGray(c, role, l, under) {
    if (role === 'bg') {
      if (l < 0.2 && c.a >= 0.3 && c.a < 0.95) return null;
      // A faint white wash lightens whatever is under it.
      if (l > 0.8 && c.a < 1) return clear(v('text'), Math.round(c.a * 30));
      if (under < 0.235) return v('sink');
      if (under < 0.3) return v('bg');
      if (under < 0.38) return v('b2');
      if (under < 0.75) return v('b1');
      return v('bg');
    }
    if (role === 'border') return under < 0.36 ? v('b2') : v('b1');
    // Dark text in a dark rule sits on a light surface, which is the theme background by now (Froala's misnamed "dark-theme" editor is white with #414141 text).
    if (under > 0.78 || under < 0.45) return v('text');
    if (under > 0.6) return v('subtle');
    return v('muted');
  }

  const roleOf = (prop) => {
    // A custom property's role is a guess from its name: Teams' --colorBrandBackground, --toastify-color-light. One holding a color with no hint in its name is taken as text.
    if (prop.startsWith('--')) {
      if (/shadow/i.test(prop)) return 'shadow';
      if (/background|bg|fill|surface/i.test(prop)) return 'bg';
      if (/stroke|border|outline/i.test(prop)) return 'border';
      return 'fg';
    }
    if (prop === 'background-color' || prop === 'background-image') return 'bg';
    if (prop === 'box-shadow') return 'shadow';
    if (/^(border|outline|column-rule)(-\w+)*-color$/.test(prop)) return 'border';
    if (prop === 'color' || prop === 'fill' || prop === 'stroke' || /^(text-decoration|caret|text-emphasis)-color$/.test(prop)) return 'fg';
    return null;
  };

  const ICON_FONT = /awesome|icons?\b|gantt|froala|dashicons|material|glyph/i;

  // zwipe's radii: 0.4rem inputs, 0.6rem chips and rows, 1rem panels.
  function radius(value) {
    const px = value.match(/^([\d.]+)px$/);
    if (!px) return null;
    const n = +px[1];
    if (n <= 0 || n >= 40) return null;
    return n <= 6 ? '.4rem' : n <= 12 ? '.6rem' : '1rem';
  }

  // What recolorPage was asked to touch: the grays, font families, and border radii, on top of the saturated colors it always takes.
  // `darkPage` is a selector that, when it matches, says inline styles were written for the site's own dark mode.
  let paint = { neutrals: false, fonts: false, radii: false, darkPage: null };

  // The original of every stylesheet declaration rewritten, so turning orangui off can put the page back.
  const saved = [];

  function restyle(style, keep, dark) {
    for (let i = 0; i < style.length; i++) {
      const prop = style[i];
      const value = style.getPropertyValue(prop);
      if (!value || value.includes('--og-')) continue;
      let next = null;
      const role = roleOf(prop);
      if (role && !(role === 'bg' && value.includes('url('))) {
        const swapped = value.replace(COLOR, (m) => recolor(m, role, paint.neutrals, dark) ?? m);
        if (swapped !== value) next = swapped;
      } else if (paint.fonts && prop === 'font-family' && !ICON_FONT.test(value)) {
        next = FONT;
      } else if (paint.radii && /^border-.*-radius$/.test(prop)) {
        next = radius(value);
      }
      if (next === null || next === value) continue;
      const priority = style.getPropertyPriority(prop);
      if (keep) saved.push([style, prop, value, priority]);
      style.setProperty(prop, next, priority);
    }
  }

  // Every rule already rewritten. Tracked per rule, not per sheet: Fluent swaps its token rule out for a new one at the same index, which leaves the sheet's length unchanged.
  let seen = new WeakSet();
  // A rule whose selector or media query mentions dark (.theme-dark, .fr-dark, prefers-color-scheme: dark) was written for a dark page.
  const walk = (rules, dark = false) => {
    for (const rule of rules) {
      const inDark = dark || /dark/i.test(rule.selectorText ?? rule.conditionText ?? '');
      if (rule.style && !seen.has(rule)) {
        seen.add(rule);
        restyle(rule.style, true, inDark);
      }
      if (rule.cssRules) walk(rule.cssRules, inDark);
    }
  };

  // Rewrites every rule not yet seen. Cross-origin sheets can't be read and are skipped.
  function scan() {
    if (!enabled) return;
    for (const sheet of [...document.styleSheets, ...document.adoptedStyleSheets]) {
      if (sheet.ownerNode?.dataset?.orangui) continue;
      let rules;
      try { rules = sheet.cssRules; } catch { continue; }
      walk(rules);
    }
  }

  // Inline styles come and go with every React render, so they are rewritten as they appear and never restored.
  // SVG color attributes (FontAwesome's color="white") are carried into the inline style, which outranks them.
  const PAINTED = ['color', 'fill', 'stroke'];
  const INLINE = '[style], svg[color], svg [fill], svg [stroke]';
  const pending = new Set();
  let frame = 0;
  const flush = () => {
    frame = 0;
    const dark = Boolean(paint.darkPage && document.querySelector(paint.darkPage));
    for (const el of pending) {
      if (!el.style) continue;
      for (const attr of PAINTED) {
        const value = el.getAttribute(attr);
        if (!value || el.style.getPropertyValue(attr)) continue;
        const next = value.replace(COLOR, (m) => recolor(m, 'fg', paint.neutrals, dark) ?? m);
        if (next !== value) el.style.setProperty(attr, next);
      }
      restyle(el.style, false, dark);
    }
    pending.clear();
  };
  const queue = (el) => {
    pending.add(el);
    frame ||= requestAnimationFrame(flush);
  };

  const watcher = new MutationObserver((records) => {
    let sheets = false;
    for (const r of records) {
      if (r.type === 'attributes') {
        // An attribute change means the page re-rendered it; the stale rewrite of that attribute comes off.
        if (r.attributeName !== 'style') r.target.style?.removeProperty(r.attributeName);
        queue(r.target);
        continue;
      }
      for (const node of r.addedNodes) {
        if (node.nodeType !== 1) continue;
        if (node.matches('style, link[rel="stylesheet"]')) {
          sheets = true;
          node.addEventListener('load', scan, { once: true });
        }
        if (node.matches(INLINE)) queue(node);
        node.querySelectorAll?.(INLINE).forEach(queue);
      }
    }
    if (sheets) requestAnimationFrame(scan);
  });

  let timer = 0;
  function run(on) {
    if (on && timer) return;
    if (on) {
      watcher.observe(document, { subtree: true, childList: true, attributes: true, attributeFilter: ['style', ...PAINTED] });
      document.querySelectorAll(INLINE).forEach(queue);
      scan();
      // Emotion and react-select add rules through insertRule, which no observer sees.
      timer = setInterval(() => { if (!document.hidden) scan(); }, 1500);
    } else {
      watcher.disconnect();
      clearInterval(timer);
      timer = 0;
      for (const [style, prop, value, priority] of saved) style.setProperty(prop, value, priority);
      saved.length = 0;
      seen = new WeakSet();
    }
  }

  // Sets what the recolor touches and returns the switch a site hands to start() as onEnabled.
  function recolorPage(options) {
    paint = { ...paint, ...options };
    return run;
  }

  // == start: a site script calls this once with its own CSS ==

  function start({ css, onEnabled: hook }) {
    baseStyle.textContent = css + CORE_CSS;
    if (hook) onEnabled = hook;
    apply(current);
    setEnabled(enabled);

    GM_addValueChangeListener('theme', (_key, _old, next, remote) => {
      if (remote && !picker?.isOpen()) apply(valid(next), true);
    });
    GM_addValueChangeListener('enabled', (_key, _old, next, remote) => { if (remote) setEnabled(next); });
    GM_addValueChangeListener('launcher', (_key, _old, next, remote) => {
      if (remote) { showLauncher = next; picker?.sync(); }
    });

    if (!TOP) return;
    picker = makePicker();
    GM_registerMenuCommand('Themes… (Alt+Shift+T)', () => picker.open());
    GM_registerMenuCommand('Show or hide the ◐ launcher', () => {
      showLauncher = !showLauncher;
      GM_setValue('launcher', showLauncher);
      picker.sync();
    });
    GM_registerMenuCommand('Put the ◐ back in the corner', () => picker.home());
    GM_registerMenuCommand('Turn orangui on or off', () => {
      setEnabled(!enabled);
      GM_setValue('enabled', enabled);
    });
  }
  // </core>

  // <fluent> copied by scripts/sync.mjs from src/fluent.js, don't edit by hand
  // What the Fluent UI scripts share: every Fluent v9 token and Outlook's v8 palette pointed at a theme variable, and zwipe's shapes on Fluent's components.
  // scripts/sync.mjs copies this file into each Fluent userscript between the fluent markers, after the core.

  // == Fluent v9 tokens, every one pointed at a theme variable ==

  const fluent = {
    // zwipe's radii: 0.4rem inputs, 0.5rem buttons, 0.6rem chips, 1rem panels. Circular stays circular.
    borderRadiusSmall: '0.25rem',
    borderRadiusMedium: '0.5rem',
    borderRadiusLarge: '0.6rem',
    borderRadiusXLarge: '1rem',
    borderRadius2XLarge: '1rem',
    borderRadius3XLarge: '1rem',
    borderRadius4XLarge: '1rem',
    borderRadius5XLarge: '1rem',
    borderRadius6XLarge: '1rem',
    fontFamilyBase: FONT,
    fontFamilyMonospace: FONT,
    fontFamilyNumeric: FONT,

    colorNeutralForeground1: v('text'),
    colorNeutralForeground1Hover: v('text'),
    colorNeutralForeground1Pressed: v('text'),
    colorNeutralForeground1Selected: v('text'),
    colorNeutralForeground2: v('text'),
    colorNeutralForeground2Hover: v('text'),
    colorNeutralForeground2Pressed: v('text'),
    colorNeutralForeground2Selected: v('text'),
    colorNeutralForeground2BrandHover: v('a1'),
    colorNeutralForeground2BrandPressed: v('a1'),
    colorNeutralForeground2BrandSelected: v('a1'),
    colorNeutralForeground3: v('subtle'),
    colorNeutralForeground3Hover: v('text'),
    colorNeutralForeground3Pressed: v('text'),
    colorNeutralForeground3Selected: v('text'),
    colorNeutralForeground3BrandHover: v('a1'),
    colorNeutralForeground3BrandPressed: v('a1'),
    colorNeutralForeground3BrandSelected: v('a1'),
    colorNeutralForeground4: v('muted'),
    colorNeutralForeground5: v('subtle'),
    colorNeutralForeground5Hover: v('text'),
    colorNeutralForeground5Pressed: v('text'),
    colorNeutralForeground5Selected: v('text'),
    colorNeutralForegroundDisabled: v('b1'),
    colorNeutralForegroundInvertedDisabled: clear(v('text'), 40),
    colorBrandForegroundLink: v('a1'),
    colorBrandForegroundLinkHover: v('a1'),
    colorBrandForegroundLinkPressed: v('a1'),
    colorBrandForegroundLinkSelected: v('a1'),
    colorNeutralForeground2Link: v('text'),
    colorNeutralForeground2LinkHover: v('text'),
    colorNeutralForeground2LinkPressed: v('text'),
    colorNeutralForeground2LinkSelected: v('text'),
    colorCompoundBrandForeground1: v('a1'),
    colorCompoundBrandForeground1Hover: v('a1'),
    colorCompoundBrandForeground1Pressed: v('a1'),
    colorBrandForeground1: v('a1'),
    colorBrandForeground2: v('a1'),
    colorBrandForeground2Hover: v('a1'),
    colorBrandForeground2Pressed: v('text'),
    colorNeutralForeground1Static: v('bg'),
    colorNeutralForegroundStaticInverted: v('text'),
    colorNeutralForegroundInverted: v('bg'),
    colorNeutralForegroundInvertedHover: v('bg'),
    colorNeutralForegroundInvertedPressed: v('bg'),
    colorNeutralForegroundInvertedSelected: v('bg'),
    colorNeutralForegroundInverted2: v('bg'),
    colorNeutralForegroundOnBrand: v('bg'),
    colorNeutralForegroundInvertedLink: v('bg'),
    colorNeutralForegroundInvertedLinkHover: v('bg'),
    colorNeutralForegroundInvertedLinkPressed: v('bg'),
    colorNeutralForegroundInvertedLinkSelected: v('bg'),
    colorBrandForegroundInverted: v('a1'),
    colorBrandForegroundInvertedHover: v('a1'),
    colorBrandForegroundInvertedPressed: v('a1'),
    colorBrandForegroundOnLight: v('a1'),
    colorBrandForegroundOnLightHover: v('a1'),
    colorBrandForegroundOnLightPressed: v('a1'),
    colorBrandForegroundOnLightSelected: v('a1'),

    colorNeutralBackground1: v('bg'),
    colorNeutralBackground1Hover: v('b2'),
    colorNeutralBackground1Pressed: v('sink'),
    colorNeutralBackground1Selected: v('b2'),
    colorNeutralBackground2: v('bg'),
    colorNeutralBackground2Hover: v('b2'),
    colorNeutralBackground2Pressed: v('sink'),
    colorNeutralBackground2Selected: v('b2'),
    colorNeutralBackground3: v('sink'),
    colorNeutralBackground3Hover: v('b2'),
    colorNeutralBackground3Pressed: v('sink'),
    colorNeutralBackground3Selected: v('bg'),
    colorNeutralBackground4: v('sink'),
    colorNeutralBackground4Hover: v('bg'),
    colorNeutralBackground4Pressed: v('sink'),
    colorNeutralBackground4Selected: v('bg'),
    colorNeutralBackground5: v('sink'),
    colorNeutralBackground5Hover: v('sink'),
    colorNeutralBackground5Pressed: v('sink'),
    colorNeutralBackground5Selected: v('sink'),
    colorNeutralBackground6: v('b2'),
    colorNeutralBackground7: 'transparent',
    colorNeutralBackground7Hover: v('sink'),
    colorNeutralBackground7Pressed: v('sink'),
    colorNeutralBackground7Selected: 'transparent',
    colorNeutralBackground8: v('bg'),
    colorNeutralBackgroundInverted: v('text'),
    colorNeutralBackgroundInvertedHover: v('text'),
    colorNeutralBackgroundInvertedPressed: v('subtle'),
    colorNeutralBackgroundInvertedSelected: v('text'),
    colorNeutralBackgroundStatic: v('b2'),
    colorNeutralBackgroundAlpha: clear(v('sink'), 50),
    colorNeutralBackgroundAlpha2: clear(v('sink'), 70),
    colorSubtleBackgroundHover: v('b2'),
    colorSubtleBackgroundPressed: v('sink'),
    colorSubtleBackgroundSelected: v('b2'),
    colorSubtleBackgroundLightAlphaHover: clear(v('bg'), 80),
    colorSubtleBackgroundLightAlphaPressed: clear(v('bg'), 50),
    colorSubtleBackgroundInvertedHover: clear(v('sink'), 10),
    colorSubtleBackgroundInvertedPressed: clear(v('sink'), 30),
    colorSubtleBackgroundInvertedSelected: clear(v('sink'), 20),
    colorNeutralBackgroundDisabled: v('sink'),
    colorNeutralBackgroundDisabled2: v('bg'),
    colorNeutralBackgroundInvertedDisabled: clear(v('text'), 10),
    colorNeutralStencil1: v('b1'),
    colorNeutralStencil2: v('b2'),
    colorNeutralStencil1Alpha: clear(v('text'), 10),
    colorNeutralStencil2Alpha: clear(v('text'), 5),
    colorBackgroundOverlay: v('overlay'),
    colorScrollbarOverlay: clear(v('text'), 60),

    // Brand fills read like zwipe's active keyword chip: the accent, with the background as its text.
    colorBrandBackground: v('a1'),
    colorBrandBackgroundHover: mix(v('a1'), 88, v('text')),
    colorBrandBackgroundPressed: mix(v('a1'), 80),
    colorBrandBackgroundSelected: v('a1'),
    colorCompoundBrandBackground: v('a1'),
    colorCompoundBrandBackgroundHover: mix(v('a1'), 88, v('text')),
    colorCompoundBrandBackgroundPressed: mix(v('a1'), 80),
    colorBrandBackgroundStatic: v('a1'),
    colorBrandBackground2: mix(v('a1'), 15),
    colorBrandBackground2Hover: mix(v('a1'), 25),
    colorBrandBackground2Pressed: mix(v('a1'), 10),
    colorBrandBackground3Static: v('a1'),
    colorBrandBackground4Static: v('a1'),
    colorBrandBackgroundInverted: v('text'),
    colorBrandBackgroundInvertedHover: v('text'),
    colorBrandBackgroundInvertedPressed: v('a1'),
    colorBrandBackgroundInvertedSelected: v('subtle'),
    colorNeutralCardBackground: v('bg'),
    colorNeutralCardBackgroundHover: v('bg'),
    colorNeutralCardBackgroundPressed: v('sink'),
    colorNeutralCardBackgroundSelected: v('b2'),
    colorNeutralCardBackgroundDisabled: v('sink'),

    colorNeutralStrokeAccessible: v('muted'),
    colorNeutralStrokeAccessibleHover: v('subtle'),
    colorNeutralStrokeAccessiblePressed: v('muted'),
    colorNeutralStrokeAccessibleSelected: v('a1'),
    colorNeutralStroke1: v('b1'),
    colorNeutralStroke1Hover: v('muted'),
    colorNeutralStroke1Pressed: v('muted'),
    colorNeutralStroke1Selected: v('a1'),
    colorNeutralStroke2: v('b3'),
    colorNeutralStroke3: v('b2'),
    colorNeutralStroke4: v('b2'),
    colorNeutralStroke4Hover: v('bg'),
    colorNeutralStroke4Pressed: v('bg'),
    colorNeutralStroke4Selected: v('b2'),
    colorNeutralStrokeSubtle: v('sink'),
    colorNeutralStrokeOnBrand: v('bg'),
    colorNeutralStrokeOnBrand2: v('text'),
    colorNeutralStrokeOnBrand2Hover: v('text'),
    colorNeutralStrokeOnBrand2Pressed: v('text'),
    colorNeutralStrokeOnBrand2Selected: v('text'),
    colorBrandStroke1: v('a1'),
    colorBrandStroke2: v('a1'),
    colorBrandStroke2Hover: v('a1'),
    colorBrandStroke2Pressed: v('b2'),
    colorBrandStroke2Contrast: v('a1'),
    colorCompoundBrandStroke: v('a1'),
    colorCompoundBrandStrokeHover: v('a1'),
    colorCompoundBrandStrokePressed: v('a1'),
    colorNeutralStrokeDisabled: v('b3'),
    colorNeutralStrokeDisabled2: v('b2'),
    colorNeutralStrokeInvertedDisabled: clear(v('text'), 40),
    colorNeutralStrokeAlpha: clear(v('text'), 10),
    colorNeutralStrokeAlpha2: clear(v('text'), 20),
    colorStrokeFocus1: v('bg'),
    colorStrokeFocus2: v('a2'),

    colorNeutralShadowAmbient: 'rgba(0,0,0,.24)',
    colorNeutralShadowKey: 'rgba(0,0,0,.28)',
    colorNeutralShadowAmbientLighter: 'rgba(0,0,0,.12)',
    colorNeutralShadowKeyLighter: 'rgba(0,0,0,.14)',
    colorNeutralShadowAmbientDarker: 'rgba(0,0,0,.4)',
    colorNeutralShadowKeyDarker: 'rgba(0,0,0,.48)',
    colorBrandShadowAmbient: 'rgba(0,0,0,.3)',
    colorBrandShadowKey: 'rgba(0,0,0,.25)',
    // Flat in place, zwipe's soft drop under anything that floats.
    shadow2: 'none',
    shadow4: 'none',
    shadow8: v('shadow-sm'),
    shadow16: v('shadow-sm'),
    shadow28: v('shadow-md'),
    shadow64: v('shadow-md'),
    shadow2Brand: 'none',
    shadow4Brand: 'none',
    shadow8Brand: v('shadow-sm'),
    shadow16Brand: v('shadow-sm'),
    shadow28Brand: v('shadow-md'),
    shadow64Brand: v('shadow-md'),
  };

  // Fluent's named palette colors, each sent to the theme color nearest it.
  const PALETTE = {
    err: ['Red', 'DarkRed', 'Cranberry'],
    ok: ['Green', 'LightGreen', 'Forest', 'DarkGreen'],
    warn: ['Yellow', 'Marigold', 'Gold', 'Brass'],
    p2: ['DarkOrange', 'Pumpkin', 'Peach', 'Brown'],
    p4: ['Berry', 'Purple', 'Grape', 'Lilac', 'Pink', 'Magenta', 'Plum'],
    p6: ['Seafoam', 'LightTeal', 'Teal'],
    p1: ['Steel', 'Blue', 'RoyalBlue', 'Cornflower', 'Navy', 'Lavender'],
    muted: ['Beige', 'Mink', 'Platinum', 'Anchor'],
  };
  const STATUS = { ok: 'Success', warn: 'Warning', err: 'Danger' };

  const tint = (prefix, c) => {
    fluent[`${prefix}Background1`] = mix(c, 12);
    fluent[`${prefix}Background2`] = mix(c, 25);
    fluent[`${prefix}Background3`] = c;
    fluent[`${prefix}Foreground1`] = c;
    fluent[`${prefix}Foreground2`] = c;
    fluent[`${prefix}Foreground3`] = c;
    fluent[`${prefix}ForegroundInverted`] = c;
    fluent[`${prefix}BorderActive`] = c;
    fluent[`${prefix}Border1`] = mix(c, 40);
    fluent[`${prefix}Border2`] = c;
  };
  for (const [key, names] of Object.entries(PALETTE)) for (const n of names) tint(`colorPalette${n}`, v(key));
  for (const [key, n] of Object.entries(STATUS)) {
    tint(`colorStatus${n}`, v(key));
    fluent[`colorStatus${n}Background3Hover`] = mix(v(key), 88, v('text'));
    fluent[`colorStatus${n}Background3Pressed`] = mix(v(key), 80);
  }

  // == Fluent v8, which Outlook still runs beside v9 ==

  const fluent8 = {
    themeDarker: v('a1'),
    themeDark: v('a1'),
    themeDarkAlt: v('a1'),
    themePrimary: v('a1'),
    themeSecondary: mix(v('a1'), 70),
    themeTertiary: mix(v('a1'), 50),
    // The selected-mail tint.
    themeLight: mix(v('a1'), 22),
    themeLighter: mix(v('a1'), 16),
    themeLighterAlt: mix(v('a1'), 10),
    black: v('text'),
    neutralDark: v('text'),
    neutralPrimary: v('text'),
    neutralPrimaryAlt: v('subtle'),
    neutralSecondary: v('muted'),
    neutralSecondaryAlt: v('muted'),
    neutralTertiary: v('b1'),
    neutralTertiaryAlt: v('b3'),
    neutralQuaternary: v('b2'),
    neutralQuaternaryAlt: v('b2'),
    neutralLight: v('b2'),
    neutralLighter: v('bg'),
    neutralLighterAlt: v('sink'),
    // Outlook's surface pair: cards and rows on the primary, the panes behind them on the secondary.
    neutralPrimarySurface: v('bg'),
    neutralSecondarySurface: v('sink'),
    white: v('bg'),
    redDark: v('err'),
  };

  const decls = (o) => Object.entries(o).map(([k, val]) => `--${k}: ${val} !important;`).join('\n');

  // == zwipe's shapes on Fluent's components ==

  const FLUENT_CSS = `
    :root, .fui-FluentProvider { ${decls(fluent)} }
    :root, body, [style*="--neutralPrimary"], [style*="--themePrimary"] { ${decls(fluent8)} }

    html, body { min-height: 100%; background-attachment: fixed; }
    ${grid('html, body')}
    body, input, textarea, button, select, [contenteditable] { font-family: ${FONT}; }

    /* panels: the dialog is zwipe's panel card, menus and popovers its banners */
    .fui-DialogSurface {
      border: 1px solid var(--og-b2) !important; border-radius: 1rem !important; box-shadow: var(--og-shadow-md) !important;
    }
    :is(.fui-PopoverSurface, .fui-MenuPopover, .fui-Listbox, .fui-Tooltip) {
      border: 1px solid var(--og-b2) !important; box-shadow: var(--og-shadow-sm) !important;
    }
    .fui-Card { border: 1px solid var(--og-b2) !important; transition: border-color .2s; }
    .fui-Card:hover { border-color: var(--og-a1) !important; }

    /* people as squircles; the presence dot stays round */
    ${squircle('.fui-Avatar, .fui-Avatar__image, .fui-Avatar__initials, .fui-Avatar__icon, .fui-Avatar::before, .fui-Avatar::after')}

    /* text buttons are zwipe's util buttons: outlined, the accent on hover */
    .fui-Button:not(:has(.fui-Button__icon)) { border: 1px solid var(--og-b1) !important; }
    .fui-Button:not(:has(.fui-Button__icon)):not(:disabled):hover { border-color: var(--og-a1) !important; }

    /* inputs: one outline that takes the accent on focus, in place of Fluent's underline */
    :is(.fui-Input, .fui-Textarea, .fui-Dropdown, .fui-Combobox, .fui-SearchBox) {
      border: 1px solid var(--og-b1) !important; border-radius: .4rem !important;
    }
    :is(.fui-Input, .fui-Textarea, .fui-Dropdown, .fui-Combobox, .fui-SearchBox):focus-within { border-color: var(--og-a1) !important; }
    :is(.fui-Input, .fui-Textarea, .fui-Dropdown, .fui-Combobox, .fui-SearchBox)::after { display: none !important; }

    /* zwipe's eyebrow on menu group headers */
    .fui-MenuGroupHeader {
      text-transform: uppercase; letter-spacing: .08em; font-size: .75rem !important; color: var(--og-a3) !important;
    }

    /* | / - \\ spinner */
    .fui-Spinner__spinner {
      mask: none !important; -webkit-mask: none !important; animation: none !important; background: none !important;
      display: grid !important; place-items: center;
    }
    .fui-Spinner__spinner > *, .fui-Spinner__spinner::before { display: none !important; }
    .fui-Spinner__spinner::after {
      content: '|'; font: 700 1.2em ${FONT}; color: var(--og-a2);
      animation: og-spin .5s steps(1) infinite;
    }
    @keyframes og-spin { 0% { content: '|'; } 25% { content: '/'; } 50% { content: '-'; } 75% { content: '\\\\'; } }

    @media (prefers-reduced-motion: no-preference) {
      .fui-Button { transition: background-color .2s ease, border-color .2s ease, color .2s ease !important; }
    }
  `;
  // </fluent>

  // == Teams' own tokens, on top of Fluent's: the purple Fluent's names don't reach ==

  const teams = {
    colorTeamsBrand1: v('a1'),
    colorTeamsBrand1Hover: mix(v('a1'), 88, v('text')),
    colorTeamsBrand1Pressed: mix(v('a1'), 80),
    colorTeamsBrand1Selected: v('a1'),
    colorBrandFlair1: v('a1'),
    colorBrandFlair2: v('a3'),
    colorBrandFlair3: v('p4'),
    colorBrandFlair1Transparent: clear(v('a1'), 0),
    colorBrandFlair2Transparent: clear(v('a3'), 0),
    colorBrandFlair3Transparent: clear(v('p4'), 0),
    colorSubtleBackground: 'transparent',
    colorSubtleBackgroundLightAlphaSelected: clear(v('bg'), 70),
    colorSubtleBackgroundInverted: 'transparent',
    colorDefaultBackground7: v('bg'),
    colorPrimaryBackgroundInteracted: mix(v('a1'), 25),
    colorAvatar: v('text'),
    colorAvatarBackground: v('b2'),
    // Copilot's glowing border.
    'ms-themeColorPaletteComponentGlowBorder1': v('a1'),
    'ms-themeColorPaletteComponentGlowBorder2': v('a3'),
    'ms-themeColorPaletteComponentGlowBorder3': v('p4'),
    'ms-themeColorPaletteComponentGlowBorder4': v('a2'),
    'ms-themeColorPaletteComponentGlowBorder5': v('a1'),
    globalAccentMyBubbleForeground: v('text'),
    chatThemeMyBubbleForeground: v('text'),
    chatThemeIncomingBubbleBackground: v('bg'),
    'icon-brand-color': v('a1'),
    forwardMessageLinkColor: v('a1'),
    forwardMessageLinkColorHover: v('a1'),
    forwardMessageLinkColorActive: v('a1'),
    themeTitleBarBackgroundColor: v('bg'),
  };
  for (let i = 1; i <= 9; i++) teams[`colorBrandMorseCode${i}`] = v('a1');
  for (let i = 1; i <= 4; i++) {
    teams[`colorTeamsCompositeHoverShadow${i}`] = clear(v('a1'), 25);
    teams[`colorTeamsButtonCompositeHoverShadow${i}`] = clear(v('a1'), 25);
    teams[`colorTeamsButtonCompositeFocusShadow${i}`] = clear(v('a1'), 40);
  }

  const TEAMS_CSS = `
    :root, .fui-FluentProvider { ${decls(teams)} }

    /* the message list sits on zwipe's sunken grid; the list inside it lets it show through */
    ${grid('[data-tid="message-pane-list-viewport"]')}
    [data-tid="message-pane-list-runway"] { background: transparent !important; }

    /* chat messages: zwipe's outlined panel, the accent on hover; your own carry the accent faintly */
    :is(.fui-ChatMessage__body, .fui-ChatMyMessage__body, [data-tid="chat-pane-message"]) {
      border: 1px solid var(--og-b2) !important; border-radius: .6rem !important; transition: border-color .2s;
    }
    :is(.fui-ChatMyMessage__body, .fui-ChatMyMessage [data-tid="chat-pane-message"]) {
      border-color: color-mix(in srgb, var(--og-a1) 45%, var(--og-b2)) !important;
    }
    :is(.fui-ChatMessage__body, .fui-ChatMyMessage__body, [data-tid="chat-pane-message"]):hover { border-color: var(--og-a1) !important; }
    /* nested bubbles, like a quoted reply inside a message, keep a single outline */
    :is(.fui-ChatMessage__body, .fui-ChatMyMessage__body) [data-tid="chat-pane-message"] { border: none !important; }
  `;

  // Fluent's tokens cover the grays; the recolor catches the Teams purple set as literals and in rules Teams rewrites in place.
  start({ css: FLUENT_CSS + TEAMS_CSS, onEnabled: recolorPage({ neutrals: false }) });
})();
