#!/usr/bin/env node
// Fills every userscript's generated blocks: zwipe's palettes between the "// <themes>" markers, and src/<name>.js between any other "// <name>" markers (core, fluent).
// Usage: node scripts/sync.mjs [path/to/zwipe-components/assets/themes.css]

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = process.argv[2] ?? join(root, '../zwipe/zwipe-components/assets/themes.css');

// The order every userscript reads a theme's colors in. Keep in step with KEYS in src/core.js.
const KEYS = [
  'bg-primary', 'text-primary', 'text-muted', 'text-subtle',
  'border-primary', 'border-secondary', 'border-muted',
  'color-error', 'color-success', 'color-warning',
  'border-error', 'border-success', 'border-warning',
  'accent-primary', 'accent-secondary', 'accent-tertiary',
  'palette-1', 'palette-2', 'palette-3', 'palette-4', 'palette-5', 'palette-6',
];

const css = readFileSync(source, 'utf8');
const lines = [];
for (const [, name, body] of css.matchAll(/\.theme-([a-z0-9-]+-(?:dark|light))\s*\{([^}]*)\}/g)) {
  const colors = KEYS.map((key) => {
    const value = body.match(new RegExp(`--${key}:\\s*([^;]+);`))?.[1].trim();
    if (!value) throw new Error(`theme-${name} has no --${key}`);
    return `'${value}'`;
  });
  lines.push(`  '${name}': [${colors.join(', ')}],`);
}
if (!lines.length) throw new Error(`no themes found in ${source}`);

const themes = `// <themes> generated by scripts/sync.mjs from zwipe's themes.css, don't edit by hand\nconst THEMES = {\n${lines.join('\n')}\n};\n// </themes>`;
const indent = (text) => text.trimEnd().split('\n').map((l) => (l ? `  ${l}` : l)).join('\n');
const shared = (name) =>
  `// <${name}> copied by scripts/sync.mjs from src/${name}.js, don't edit by hand\n${indent(readFileSync(join(root, `src/${name}.js`), 'utf8'))}\n  // </${name}>`;

for (const file of readdirSync(root).filter((f) => f.endsWith('.user.js'))) {
  const path = join(root, file);
  let text = readFileSync(path, 'utf8');
  if (!/\/\/ <themes>[\s\S]*?\/\/ <\/themes>/.test(text)) throw new Error(`${file} has no themes markers`);
  text = text.replace(/\/\/ <themes>[\s\S]*?\/\/ <\/themes>/, () => themes);
  // Every other marker pair names a file in src/, filled at the userscript's two-space indent.
  const names = [...new Set([...text.matchAll(/\/\/ <([a-z]+)>/g)].map((m) => m[1]))].filter((n) => n !== 'themes');
  for (const name of names) {
    text = text.replace(new RegExp(`// <${name}>[\\s\\S]*?// </${name}>`), () => shared(name));
  }
  writeFileSync(path, text);
  console.log(`${file}: ${lines.length} themes, ${names.join(', ')}`);
}
