#!/usr/bin/env node
// Copies zwipe's theme palettes into every userscript, between the "// <themes>" and "// </themes>" markers.
// Usage: node scripts/sync-themes.mjs [path/to/zwipe-components/assets/themes.css]

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = process.argv[2] ?? join(root, '../zwipe/zwipe-components/assets/themes.css');

// The order every userscript reads a theme's colors in. Keep in step with KEYS in the scripts.
const KEYS = [
  'bg-primary', 'text-primary', 'text-muted', 'text-subtle',
  'border-primary', 'border-secondary', 'border-muted',
  'color-error', 'color-success', 'color-warning',
  'border-error', 'border-success', 'border-warning',
  'accent-primary', 'accent-secondary', 'accent-tertiary',
  'palette-1', 'palette-2', 'palette-3', 'palette-4', 'palette-5', 'palette-6',
];

const css = readFileSync(source, 'utf8');
const lines = [];
for (const [, name, body] of css.matchAll(/\.theme-([a-z0-9-]+-(?:dark|light))\s*\{([^}]*)\}/g)) {
  const colors = KEYS.map((key) => {
    const value = body.match(new RegExp(`--${key}:\\s*([^;]+);`))?.[1].trim();
    if (!value) throw new Error(`theme-${name} has no --${key}`);
    return `'${value}'`;
  });
  lines.push(`  '${name}': [${colors.join(', ')}],`);
}
if (!lines.length) throw new Error(`no themes found in ${source}`);

const block = `// <themes> generated by scripts/sync-themes.mjs from zwipe's themes.css, don't edit by hand\nconst THEMES = {\n${lines.join('\n')}\n};\n// </themes>`;
for (const file of readdirSync(root).filter((f) => f.endsWith('.user.js'))) {
  const path = join(root, file);
  const before = readFileSync(path, 'utf8');
  if (!/\/\/ <themes>[\s\S]*?\/\/ <\/themes>/.test(before)) throw new Error(`${file} has no themes markers`);
  writeFileSync(path, before.replace(/\/\/ <themes>[\s\S]*?\/\/ <\/themes>/, () => block));
  console.log(`${file}: ${lines.length} themes`);
}
